//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class QuestsTranslations {
    
    private QuestsTranslationsQuestTranslations[] questTranslationsField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QuestTranslations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public QuestsTranslationsQuestTranslations[] QuestTranslations {
        get {
            return this.questTranslationsField;
        }
        set {
            this.questTranslationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QuestsTranslationsQuestTranslations {
    
    private string idField;
    
    private string jPNameField;
    
    private string tRNameField;
    
    private string jPDetailField;
    
    private string tRDetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("JP-Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JPName {
        get {
            return this.jPNameField;
        }
        set {
            this.jPNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TR-Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRName {
        get {
            return this.tRNameField;
        }
        set {
            this.tRNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("JP-Detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JPDetail {
        get {
            return this.jPDetailField;
        }
        set {
            this.jPDetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TR-Detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRDetail {
        get {
            return this.tRDetailField;
        }
        set {
            this.tRDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private QuestsTranslations[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QuestsTranslations")]
    public QuestsTranslations[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
