//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ShipsTranslation {
    
    private ShipsTranslationShipTranslation[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShipTranslation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ShipsTranslationShipTranslation[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ShipsTranslationShipTranslation {
    
    private string jPNameField;
    
    private string tRNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("JP-Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JPName {
        get {
            return this.jPNameField;
        }
        set {
            this.jPNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TR-Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRName {
        get {
            return this.tRNameField;
        }
        set {
            this.tRNameField = value;
        }
    }
}
